//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUserLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTimestamp { get; set; }
        public string LogTypeCode { get; set; }
        public System.Guid UserID { get; set; }
        public int FirmID { get; set; }
        public string LNASUserID { get; set; }
        public bool DeletedIndicator { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> UserStatus { get; set; }
        public string SID { get; set; }
        public string Email { get; set; }
        public string OrderNumber { get; set; }
        public string WamUserPermIdUrn { get; set; }
    }
}
