//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationPackageEntitlementLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTimestamp { get; set; }
        public string LogTypeCode { get; set; }
        public short PackageID { get; set; }
        public short EntitlementID { get; set; }
    }
}
