//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApplicationUser()
        {
            this.ApplicationUserFeature = new HashSet<ApplicationUserFeature>();
            this.DigestSetting = new HashSet<DigestSetting>();
            this.UserPreferenceValue = new HashSet<UserPreferenceValue>();
            this.UserRole = new HashSet<UserRole>();
        }
    
        public System.Guid UserID { get; set; }
        public int FirmID { get; set; }
        public string LNASUserID { get; set; }
        public byte[] RowChangeTimestamp { get; set; }
        public bool DeletedIndicator { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int UserStatus { get; set; }
        public string SID { get; set; }
        public string Email { get; set; }
        public string OrderNumber { get; set; }
        public string WamUserPermIdUrn { get; set; }
    
        public virtual CodeValue CodeValue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationUserFeature> ApplicationUserFeature { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DigestSetting> DigestSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPreferenceValue> UserPreferenceValue { get; set; }
        public virtual Firm Firm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserRole> UserRole { get; set; }
    }
}
