//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigestSettingLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTimestamp { get; set; }
        public string LogTypeCode { get; set; }
        public System.Guid UserID { get; set; }
        public int FirmID { get; set; }
        public bool IsEmailEnabled { get; set; }
        public string EmailAddress { get; set; }
        public bool HasSubscribedToTasksDue { get; set; }
        public bool HasSubscribedToEvents { get; set; }
        public bool HasSubscribedToMatterOverBudget { get; set; }
        public string TimeZone { get; set; }
        public System.DateTime LastRunMade { get; set; }
        public System.DateTime NextRunNeeded { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public int FrequencyType { get; set; }
        public int DaysOfWeek { get; set; }
        public Nullable<System.DateTime> NotificationTime { get; set; }
    }
}
