//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitlementPermission
    {
        public short EntitlementID { get; set; }
        public System.Guid CorePermissionID { get; set; }
        public short AccessLevel { get; set; }
    
        public virtual Entitlement Entitlement { get; set; }
    }
}
