//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTimestamp { get; set; }
        public string LogTypeCode { get; set; }
        public int FirmID { get; set; }
        public string LNASFirmID { get; set; }
        public bool DeletedIndicator { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Fax { get; set; }
        public string Website { get; set; }
        public string DisplayName { get; set; }
        public int Version { get; set; }
        public string OrderNumber { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string BillingAccountId { get; set; }
        public string PromoCode { get; set; }
        public Nullable<System.DateTime> TrialEndDate { get; set; }
        public string ReferralSource { get; set; }
        public string CountryCode { get; set; }
        public string Locale { get; set; }
        public string ExtendedInfo { get; set; }
    }
}
