//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FirmManager_DevEntities : DbContext
    {
        public FirmManager_DevEntities()
            : base("name=FirmManager_DevEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ApplicationPackage> ApplicationPackage { get; set; }
        public virtual DbSet<ApplicationPackageEntitlementLog> ApplicationPackageEntitlementLog { get; set; }
        public virtual DbSet<ApplicationRole> ApplicationRole { get; set; }
        public virtual DbSet<ApplicationRoleEntitlementLog> ApplicationRoleEntitlementLog { get; set; }
        public virtual DbSet<ApplicationUser> ApplicationUser { get; set; }
        public virtual DbSet<ApplicationUserFeature> ApplicationUserFeature { get; set; }
        public virtual DbSet<ApplicationUserFeatureLog> ApplicationUserFeatureLog { get; set; }
        public virtual DbSet<ApplicationUserLog> ApplicationUserLog { get; set; }
        public virtual DbSet<BillingCodeSet> BillingCodeSet { get; set; }
        public virtual DbSet<BillingCodeSetLog> BillingCodeSetLog { get; set; }
        public virtual DbSet<CodeType> CodeType { get; set; }
        public virtual DbSet<CodeValue> CodeValue { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<DigestSetting> DigestSetting { get; set; }
        public virtual DbSet<DigestSettingLog> DigestSettingLog { get; set; }
        public virtual DbSet<Entitlement> Entitlement { get; set; }
        public virtual DbSet<EntitlementLog> EntitlementLog { get; set; }
        public virtual DbSet<EntitlementPermission> EntitlementPermission { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<FirmLog> FirmLog { get; set; }
        public virtual DbSet<Preference> Preference { get; set; }
        public virtual DbSet<PreferenceLog> PreferenceLog { get; set; }
        public virtual DbSet<PreferenceValue> PreferenceValue { get; set; }
        public virtual DbSet<PreferenceValueLog> PreferenceValueLog { get; set; }
        public virtual DbSet<RegionSetting> RegionSetting { get; set; }
        public virtual DbSet<RegionSettingLog> RegionSettingLog { get; set; }
        public virtual DbSet<RolePermissionLog> RolePermissionLog { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserPreferenceValue> UserPreferenceValue { get; set; }
        public virtual DbSet<UserPreferenceValueLog> UserPreferenceValueLog { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserRoleLog> UserRoleLog { get; set; }
        public virtual DbSet<VersionFeature> VersionFeature { get; set; }
        public virtual DbSet<VersionRelease> VersionRelease { get; set; }
        public virtual DbSet<WamApplicationUser> WamApplicationUser { get; set; }
        public virtual DbSet<WamFirm> WamFirm { get; set; }
        public virtual DbSet<VersionInfo> VersionInfo { get; set; }
    }
}
