//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreferenceLog
    {
        public int LogID { get; set; }
        public System.DateTime LogTimestamp { get; set; }
        public string LogTypeCode { get; set; }
        public int PreferenceID { get; set; }
        public string PreferenceName { get; set; }
        public Nullable<short> PreferenceLookupCode { get; set; }
        public bool DeletedIndicator { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
