//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public System.Guid UserID { get; set; }
        public int RoleID { get; set; }
        public int FirmID { get; set; }
        public byte[] RowChangeTimestamp { get; set; }
        public bool DeletedIndicator { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ApplicationRole ApplicationRole { get; set; }
        public virtual ApplicationUser ApplicationUser { get; set; }
        public virtual Firm Firm { get; set; }
    }
}
